version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:0.10.0.1-2
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=example:1:1
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  rig:
    container_name: rig
    image: accenture/reactive-interaction-gateway
    environment:
      - PORT=7000
      - PRIVILEGED_ROLES=admin
      - JWT_ROLES_FIELD=levels
      - JWT_USER_FIELD=username
      - JWT_SECRET_KEY=mysecret
      - KAFKA_USER_FIELD=username
      - SESSION_ROLE=regularuser
      - KAFKA_SOURCE_TOPICS=example
      - KAFKA_LOG_TOPIC=example
      - KAFKA_HOSTS=kafka:9092
    ports:
      - 7000:7000
    depends_on:
      - kafka

  channels-external-service:
    container_name: channels-external-service
    image: channels-external-service
    environment:
      - KAFKA_HOSTS=kafka:9092
    ports:
      - 8000:8000

  channels-ui:
    container_name: channels-ui
    image: channels-ui
    ports:
      - 3000:80
    depends_on:
      - rig