version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:1.0.0
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=rig:1:1
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  rig:
    container_name: rig
    build:
      context: .
      dockerfile: smoke_tests.dockerfile
    environment:
      - API_HOST=rest-api
      - KAFKA_ENABLED=true
      - KAFKA_HOSTS=kafka:9092
      - PROXY_CONFIG_FILE=proxy/proxy.smoke_test.json
    ports:
      - 4000:4000
      - 4010:4010
    command: mix test --only smoke
    depends_on:
      - kafka

  rest-api:
    container_name: rest-api
    image: mariomacai/rest-api
    environment:
      - KAFKA_HOSTS=kafka:9092
    ports:
      - 8000:8000
