{
 "title": "Events",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Consumed Events per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, source) (rate(rig_consumed_events_total[5m]))",
     "legendFormat": "Total: {{source}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, source) (rate(rig_consumed_events_failed_total[5m]))",
     "legendFormat": "Failed: {{source}} - {{topic}}"
    },
    {
     "expr": "sum by (type) (rate(rig_consumed_events_forwarded_total[5m]))",
     "legendFormat": "Forwarded: {{type}}"
    }
   ]
  },
  {
   "title": "Produced Events per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, target) (rate(rig_produced_events_total[5m]))",
     "legendFormat": "Total: {{target}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, target) (rate(rig_produced_events_failed_total[5m]))",
     "legendFormat": "Failed: {{target}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Consumed Events Success Ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((sum(rig_consumed_events_total) - sum(rig_consumed_events_failed_total)) / sum(rig_consumed_events_total)) and on () sum(rig_consumed_events_failed_total) > 0) OR \n(((sum(rig_consumed_events_total) - sum(rig_consumed_events_failed_total)) / sum(rig_consumed_events_total)) and on () sum(rig_consumed_events_failed_total) > 0) OR \nsum(rig_consumed_events_total)/sum(rig_consumed_events_total)"
    }
   ]
  },
  {
   "title": "Consumer Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(rig_consumed_event_processing_duration_milliseconds_bucket[5m])) by (le, source))",
     "legendFormat": "Median: {{source}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(rig_consumed_event_processing_duration_milliseconds_bucket[5m])) by (le, source))",
     "legendFormat": "95th percentile: {{source}}"
    }
   ]
  },
  {
   "title": "Forwarded Events to UIs Ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rig_consumed_events_forwarded_total)/sum(rig_consumed_events_total)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Total Number of Consumed Events",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (topic, source) (rig_consumed_events_total)",
     "legendFormat": "Total: {{source}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, source) (rig_consumed_events_failed_total)",
     "legendFormat": "Failed: {{source}} - {{topic}}"
    },
    {
     "expr": "sum by () (rig_consumed_events_forwarded_total)",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Total Number of Produced Events",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (topic, target) (rig_produced_events_total)",
     "legendFormat": "Total: {{target}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, target) (rig_produced_events_failed_total)",
     "legendFormat": "Failed: {{target}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Produced Events Success Ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(rig_produced_events_total) / (sum(rig_produced_events_failed_total) + sum(rig_produced_events_total))) and on () sum(rig_produced_events_total) > 0) OR \nsum(rig_produced_events_total)/sum(rig_produced_events_total)"
    }
   ]
  }
 ]
}