{
 "title": "Proxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Proxy Requests per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rig_proxy_requests_total[5m])",
     "legendFormat": "All proxy requests"
    },
    {
     "expr": "sum(rate(rig_proxy_requests_total[5m])) by (status)",
     "legendFormat": "Status: {{status}}"
    },
    {
     "expr": "sum(rate(rig_proxy_requests_total[5m])) by (response_from)",
     "legendFormat": "Response from: {{response_from}}"
    },
    {
     "expr": "sum(rate(rig_proxy_requests_total[5m])) by (target)",
     "legendFormat": "Target: {{target}}"
    }
   ]
  },
  {
   "title": "Proxy Requests Success Ratio",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rig_proxy_requests_total{status=\"ok\"})/sum(rig_proxy_requests_total))"
    }
   ]
  },
  {
   "title": "Number of Proxy Requests",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rig_proxy_requests_total", "legendFormat": "All proxy requests" },
    {
     "expr": "sum(rig_proxy_requests_total) by (status)",
     "legendFormat": "Status: {{status}}"
    },
    {
     "expr": "sum(rig_proxy_requests_total) by (response_from)",
     "legendFormat": "Response from: {{response_from}}"
    },
    {
     "expr": "sum(rig_proxy_requests_total) by (target)",
     "legendFormat": "Target: {{target}}"
    }
   ]
  }
 ]
}