{
 "title": "Resources",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"reactive-interaction-gateway\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "erlang_vm_memory_bytes_total", "legendFormat": "{{kind}}: {{instance}}" }
   ]
  },
  {
   "title": "Number of Erlang Ports",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "erlang_vm_port_count", "legendFormat": "Currently used: {{instance}}" },
    { "expr": "erlang_vm_port_limit", "legendFormat": "Maximum: {{instance}}" }
   ]
  }
 ]
}