{
 "title": "Subscriptions",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Active Subscriptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rig_subscriptions_total", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Blacklist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Number of Blacklisted Tokens",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rig_sessions_total{name=\"Elixir.SessionBlacklist\"}"
    }
   ]
  },
  {
   "title": "Current Number of Blacklisted Tokens",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rig_sessions_current{name=\"Elixir.SessionBlacklist\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}