apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "helm-charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-deployment
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}