{
 "title": "RIG",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Blacklist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of Blacklisted Tokens",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rig_sessions_blacklisted_total" }
   ]
  },
  {
   "title": "Current Number of Blacklisted Tokens",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rig_sessions_blacklisted_current"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Active Subscriptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rig_subscriptions_total" }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"reactive-interaction-gateway\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"reactive-interaction-gateway\"}[5m])"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Events per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, eventhub) (rate(rig_events_total[1m]))",
     "legendFormat": "Total: {{eventhub}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, eventhub) (rate(rig_failed_events_total[1m]))",
     "legendFormat": "Failed: {{eventhub}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, eventhub) (rate(rig_dropped_events_total[1m]))",
     "legendFormat": "Dropped: {{eventhub}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, eventhub) (rate(rig_forwarded_events_total[1m]))",
     "legendFormat": "Forwarded: {{eventhub}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Total Number of Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (topic, eventhub) (rig_events_total)",
     "legendFormat": "Total: {{eventhub}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, eventhub) (rig_failed_events_total)",
     "legendFormat": "Failed: {{eventhub}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, eventhub) (rig_dropped_events_total)",
     "legendFormat": "Dropped: {{eventhub}} - {{topic}}"
    },
    {
     "expr": "sum by (topic, eventhub) (rig_forwarded_events_total)",
     "legendFormat": "Forwarded: {{eventhub}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rig_event_processing_duration_milliseconds_bucket[1m])) by (le)"
    }
   ]
  },
  {
   "title": "Events Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((rig_events_total - rig_dropped_events_total) / rig_events_total) and on () rig_dropped_events_total > 0) OR (((rig_events_total - rig_failed_events_total) / rig_events_total) and on () rig_failed_events_total > 0) OR (((rig_events_total - rig_failed_events_total - rig_dropped_events_total) / rig_events_total) and on () rig_failed_events_total > 0 and on () rig_dropped_events_total > 0) OR vector(1)"
    }
   ]
  },
  {
   "title": "Forwarded Events Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rig_forwarded_events_total)/sum(rig_proxy_requests_total))"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "HTTP Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rig_proxy_requests_total[1m])",
     "legendFormat": "All proxy requests"
    },
    {
     "expr": "sum(rate(rig_proxy_requests_total[1m])) by (status)",
     "legendFormat": "Status: {{status}}"
    },
    {
     "expr": "sum(rate(rig_proxy_requests_total[1m])) by (response_from)",
     "legendFormat": "Response from: {{response_from}}"
    },
    {
     "expr": "sum(rate(rig_proxy_requests_total[1m])) by (target)",
     "legendFormat": "Target: {{target}}"
    }
   ]
  },
  {
   "title": "Number of Proxy Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    { "expr": "rig_proxy_requests_total", "legendFormat": "All proxy requests" },
    {
     "expr": "sum(rig_proxy_requests_total) by (status)",
     "legendFormat": "Status: {{status}}"
    },
    {
     "expr": "sum(rig_proxy_requests_total) by (response_from)",
     "legendFormat": "Response from: {{response_from}}"
    },
    {
     "expr": "sum(rig_proxy_requests_total) by (target)",
     "legendFormat": "Target: {{target}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rig_proxy_requests_total{status=\"ok\"})/sum(rig_proxy_requests_total))"
    }
   ]
  }
 ]
}