apiVersion: v1
kind: Service
metadata:
  name: {{ template "reactive-interaction-gateway.name" . }}-headless
  labels:
    app: {{ template "reactive-interaction-gateway.name" . }}-headless
    chart: {{ template "reactive-interaction-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service_headless.type }}
  clusterIP: {{ .Values.service_headless.clusterIP }}
  ports:
    - port: {{ .Values.inboundPort }}
      targetPort: {{ .Values.inboundPort }}
      protocol: TCP
      name: proxy
    - port: {{ .Values.apiPort }}
      targetPort: {{ .Values.apiPort }}
      protocol: TCP
      name: internal
  selector:
    app: {{ template "reactive-interaction-gateway.name" . }}
    release: {{ .Release.Name }}
