version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:1.1.0
    environment:
      - KAFKA_LISTENERS=HOSTPLAIN://:9092,HOSTSSL://:9193,DOCKERPLAIN://:9292,DOCKERSSL://:9393
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=HOSTPLAIN:PLAINTEXT,HOSTSSL:SSL,DOCKERPLAIN:PLAINTEXT,DOCKERSSL:SSL
      - KAFKA_ADVERTISED_LISTENERS=HOSTPLAIN://localhost:9092,HOSTSSL://localhost:9193,DOCKERPLAIN://kafka:9292,DOCKERSSL://kafka:9393
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKERPLAIN
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=rig:1:1
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/certs/truststore.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=abcdefgh
      - KAFKA_SSL_KEYSTORE_LOCATION=/certs/server.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=abcdefgh
      - KAFKA_SSL_KEY_PASSWORD=abcdefgh
      - KAFKA_SSL_CLIENT_AUTH=required
    ports:
      - 9092:9092
      - 9193:9193
      - 9292
      - 9393
    volumes:
      - ./certs:/certs
    depends_on:
      - zookeeper

  rig:
    container_name: rig
    image: rig:smoke_test
    environment:
      - API_HOST=rest-api
      - PROXY_CONFIG_FILE=proxy/proxy.smoke_test.json
    ports:
      - 4000
      - 4010
    depends_on:
      - kafka
      - rest-api

  rest-api:
    container_name: rest-api
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOSTS=kafka:9292
    ports:
      - 8000:8000
